# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1152, 872)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/squirrel_64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.MainH = QtWidgets.QHBoxLayout()
        self.MainH.setObjectName("MainH")
        self.LeftV = QtWidgets.QVBoxLayout()
        self.LeftV.setObjectName("LeftV")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.LeftV.addWidget(self.label_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtImgOriginal = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtImgOriginal.setFont(font)
        self.txtImgOriginal.setObjectName("txtImgOriginal")
        self.horizontalLayout.addWidget(self.txtImgOriginal)
        self.btnImgOriginal = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnImgOriginal.setFont(font)
        self.btnImgOriginal.setObjectName("btnImgOriginal")
        self.horizontalLayout.addWidget(self.btnImgOriginal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnLoadOriginal = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadOriginal.sizePolicy().hasHeightForWidth())
        self.btnLoadOriginal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnLoadOriginal.setFont(font)
        self.btnLoadOriginal.setObjectName("btnLoadOriginal")
        self.horizontalLayout_3.addWidget(self.btnLoadOriginal)
        self.btnShowOriginal = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShowOriginal.sizePolicy().hasHeightForWidth())
        self.btnShowOriginal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnShowOriginal.setFont(font)
        self.btnShowOriginal.setObjectName("btnShowOriginal")
        self.horizontalLayout_3.addWidget(self.btnShowOriginal)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.LeftV.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.radImgIsolated1 = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radImgIsolated1.setFont(font)
        self.radImgIsolated1.setChecked(True)
        self.radImgIsolated1.setObjectName("radImgIsolated1")
        self.verticalLayout_3.addWidget(self.radImgIsolated1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radImgIsolated2 = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radImgIsolated2.setFont(font)
        self.radImgIsolated2.setObjectName("radImgIsolated2")
        self.horizontalLayout_5.addWidget(self.radImgIsolated2)
        self.txtImgIsolated = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtImgIsolated.setFont(font)
        self.txtImgIsolated.setObjectName("txtImgIsolated")
        self.horizontalLayout_5.addWidget(self.txtImgIsolated)
        self.btnImgIsolated = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnImgIsolated.setFont(font)
        self.btnImgIsolated.setObjectName("btnImgIsolated")
        self.horizontalLayout_5.addWidget(self.btnImgIsolated)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnLoadIsolated = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadIsolated.sizePolicy().hasHeightForWidth())
        self.btnLoadIsolated.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnLoadIsolated.setFont(font)
        self.btnLoadIsolated.setObjectName("btnLoadIsolated")
        self.horizontalLayout_2.addWidget(self.btnLoadIsolated)
        self.btnShowIsolated = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShowIsolated.sizePolicy().hasHeightForWidth())
        self.btnShowIsolated.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnShowIsolated.setFont(font)
        self.btnShowIsolated.setObjectName("btnShowIsolated")
        self.horizontalLayout_2.addWidget(self.btnShowIsolated)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.LeftV.addWidget(self.groupBox_2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_8)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 2, 1, 1)
        self.txtLeft = QtWidgets.QLineEdit(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtLeft.setFont(font)
        self.txtLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.txtLeft.setObjectName("txtLeft")
        self.gridLayout_4.addWidget(self.txtLeft, 2, 1, 1, 1)
        self.txtTop = QtWidgets.QLineEdit(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTop.setFont(font)
        self.txtTop.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTop.setObjectName("txtTop")
        self.gridLayout_4.addWidget(self.txtTop, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.txtRight = QtWidgets.QLineEdit(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtRight.setFont(font)
        self.txtRight.setAlignment(QtCore.Qt.AlignCenter)
        self.txtRight.setObjectName("txtRight")
        self.gridLayout_4.addWidget(self.txtRight, 2, 3, 1, 1)
        self.txtBottom = QtWidgets.QLineEdit(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtBottom.setFont(font)
        self.txtBottom.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBottom.setObjectName("txtBottom")
        self.gridLayout_4.addWidget(self.txtBottom, 3, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 4, 2, 1, 1)
        self.btnCrop = QtWidgets.QPushButton(self.groupBox_8)
        self.btnCrop.setObjectName("btnCrop")
        self.gridLayout_4.addWidget(self.btnCrop, 2, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.LeftV.addWidget(self.groupBox_8)
        self.MainH.addLayout(self.LeftV)
        self.RightV = QtWidgets.QVBoxLayout()
        self.RightV.setObjectName("RightV")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(1)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.btnManipulate = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnManipulate.setFont(font)
        self.btnManipulate.setObjectName("btnManipulate")
        self.verticalLayout_5.addWidget(self.btnManipulate)
        self.RightV.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtMicrometers = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMicrometers.sizePolicy().hasHeightForWidth())
        self.txtMicrometers.setSizePolicy(sizePolicy)
        self.txtMicrometers.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMicrometers.setFont(font)
        self.txtMicrometers.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtMicrometers.setObjectName("txtMicrometers")
        self.gridLayout_2.addWidget(self.txtMicrometers, 0, 1, 1, 1)
        self.btnDetermine = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDetermine.sizePolicy().hasHeightForWidth())
        self.btnDetermine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnDetermine.setFont(font)
        self.btnDetermine.setObjectName("btnDetermine")
        self.gridLayout_2.addWidget(self.btnDetermine, 1, 3, 1, 1)
        self.txtPixels = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPixels.sizePolicy().hasHeightForWidth())
        self.txtPixels.setSizePolicy(sizePolicy)
        self.txtPixels.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPixels.setFont(font)
        self.txtPixels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtPixels.setObjectName("txtPixels")
        self.gridLayout_2.addWidget(self.txtPixels, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 2, 1, 1)
        self.btnEqual = QtWidgets.QToolButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEqual.sizePolicy().hasHeightForWidth())
        self.btnEqual.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEqual.setFont(font)
        self.btnEqual.setObjectName("btnEqual")
        self.gridLayout_2.addWidget(self.btnEqual, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.txtMPP = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMPP.sizePolicy().hasHeightForWidth())
        self.txtMPP.setSizePolicy(sizePolicy)
        self.txtMPP.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMPP.setFont(font)
        self.txtMPP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtMPP.setObjectName("txtMPP")
        self.gridLayout_2.addWidget(self.txtMPP, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 4, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.RightV.addWidget(self.groupBox_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.chbExcel = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.chbExcel.setFont(font)
        self.chbExcel.setChecked(True)
        self.chbExcel.setObjectName("chbExcel")
        self.verticalLayout_4.addWidget(self.chbExcel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtExcel = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtExcel.setFont(font)
        self.txtExcel.setObjectName("txtExcel")
        self.horizontalLayout_4.addWidget(self.txtExcel)
        self.btnExcel = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnExcel.setFont(font)
        self.btnExcel.setObjectName("btnExcel")
        self.horizontalLayout_4.addWidget(self.btnExcel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.chbEval = QtWidgets.QCheckBox(self.groupBox_3)
        self.chbEval.setChecked(True)
        self.chbEval.setObjectName("chbEval")
        self.verticalLayout_4.addWidget(self.chbEval)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.chbIndex = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbIndex.setFont(font)
        self.chbIndex.setChecked(True)
        self.chbIndex.setObjectName("chbIndex")
        self.gridLayout.addWidget(self.chbIndex, 0, 1, 1, 1)
        self.chbContours = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbContours.setFont(font)
        self.chbContours.setChecked(True)
        self.chbContours.setObjectName("chbContours")
        self.gridLayout.addWidget(self.chbContours, 0, 0, 1, 1)
        self.chbFitting = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbFitting.setFont(font)
        self.chbFitting.setChecked(True)
        self.chbFitting.setObjectName("chbFitting")
        self.gridLayout.addWidget(self.chbFitting, 1, 0, 1, 1)
        self.chbAngle = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbAngle.setFont(font)
        self.chbAngle.setObjectName("chbAngle")
        self.gridLayout.addWidget(self.chbAngle, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.txtEval = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtEval.setObjectName("txtEval")
        self.horizontalLayout_7.addWidget(self.txtEval)
        self.btnEvalBrowse = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEvalBrowse.setFont(font)
        self.btnEvalBrowse.setObjectName("btnEvalBrowse")
        self.horizontalLayout_7.addWidget(self.btnEvalBrowse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.RightV.addWidget(self.groupBox_3)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnHelp = QtWidgets.QPushButton(self.groupBox_6)
        self.btnHelp.setObjectName("btnHelp")
        self.verticalLayout_7.addWidget(self.btnHelp)
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setOpenExternalLinks(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.RightV.addWidget(self.groupBox_6)
        self.MainH.addLayout(self.RightV)
        self.verticalLayout_9.addLayout(self.MainH)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnThreshold = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThreshold.sizePolicy().hasHeightForWidth())
        self.btnThreshold.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnThreshold.setFont(font)
        self.btnThreshold.setObjectName("btnThreshold")
        self.horizontalLayout_6.addWidget(self.btnThreshold)
        self.btnResult = QtWidgets.QPushButton(self.groupBox_5)
        self.btnResult.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResult.sizePolicy().hasHeightForWidth())
        self.btnResult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnResult.setFont(font)
        self.btnResult.setObjectName("btnResult")
        self.horizontalLayout_6.addWidget(self.btnResult)
        self.btnExport = QtWidgets.QPushButton(self.groupBox_5)
        self.btnExport.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExport.sizePolicy().hasHeightForWidth())
        self.btnExport.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnExport.setFont(font)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout_6.addWidget(self.btnExport)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.txtPixels.returnPressed.connect(self.btnEqual.click)
        self.txtMicrometers.returnPressed.connect(self.btnEqual.click)
        self.btnImgIsolated.released.connect(self.radImgIsolated2.click)
        self.txtImgOriginal.returnPressed.connect(self.btnLoadOriginal.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtImgOriginal, self.btnImgOriginal)
        MainWindow.setTabOrder(self.btnImgOriginal, self.btnLoadOriginal)
        MainWindow.setTabOrder(self.btnLoadOriginal, self.btnShowOriginal)
        MainWindow.setTabOrder(self.btnShowOriginal, self.radImgIsolated1)
        MainWindow.setTabOrder(self.radImgIsolated1, self.radImgIsolated2)
        MainWindow.setTabOrder(self.radImgIsolated2, self.txtImgIsolated)
        MainWindow.setTabOrder(self.txtImgIsolated, self.btnImgIsolated)
        MainWindow.setTabOrder(self.btnImgIsolated, self.btnLoadIsolated)
        MainWindow.setTabOrder(self.btnLoadIsolated, self.btnShowIsolated)
        MainWindow.setTabOrder(self.btnShowIsolated, self.txtLeft)
        MainWindow.setTabOrder(self.txtLeft, self.txtTop)
        MainWindow.setTabOrder(self.txtTop, self.txtRight)
        MainWindow.setTabOrder(self.txtRight, self.txtBottom)
        MainWindow.setTabOrder(self.txtBottom, self.btnCrop)
        MainWindow.setTabOrder(self.btnCrop, self.btnManipulate)
        MainWindow.setTabOrder(self.btnManipulate, self.txtMicrometers)
        MainWindow.setTabOrder(self.txtMicrometers, self.txtPixels)
        MainWindow.setTabOrder(self.txtPixels, self.btnDetermine)
        MainWindow.setTabOrder(self.btnDetermine, self.btnEqual)
        MainWindow.setTabOrder(self.btnEqual, self.txtMPP)
        MainWindow.setTabOrder(self.txtMPP, self.chbExcel)
        MainWindow.setTabOrder(self.chbExcel, self.txtExcel)
        MainWindow.setTabOrder(self.txtExcel, self.btnExcel)
        MainWindow.setTabOrder(self.btnExcel, self.btnHelp)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EICHKÖRNCHEN"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/res/squirrel_64.png\"/></p><p>EICHKÖRNCHEN - Grain Analysis Tool</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "1) Original Image / Mapping"))
        self.label.setText(_translate("MainWindow", "The original image is only used for visualizing and is not used for evaluation:"))
        self.btnImgOriginal.setText(_translate("MainWindow", "Browse..."))
        self.btnLoadOriginal.setText(_translate("MainWindow", "Load"))
        self.btnShowOriginal.setText(_translate("MainWindow", "Show"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2) Analysis Image / Mapping"))
        self.label_3.setText(_translate("MainWindow", "This image is used for analysis and should only contain a single channel with the color of the grains to be analized:"))
        self.radImgIsolated1.setText(_translate("MainWindow", "Use Original Image as Isolated Image"))
        self.radImgIsolated2.setText(_translate("MainWindow", "Load prepared Image:"))
        self.btnImgIsolated.setText(_translate("MainWindow", "Browse..."))
        self.btnLoadIsolated.setText(_translate("MainWindow", "Load"))
        self.btnShowIsolated.setText(_translate("MainWindow", "Show"))
        self.groupBox_8.setTitle(_translate("MainWindow", "3) Crop Analysis Image"))
        self.label_20.setText(_translate("MainWindow", "Crop the Analysis Image to the a rectangle with the corner coordinates. You can also edit the desired rectangle graphically."))
        self.label_18.setText(_translate("MainWindow", "Right"))
        self.label_17.setText(_translate("MainWindow", "Top"))
        self.txtLeft.setText(_translate("MainWindow", "0"))
        self.txtTop.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "Left"))
        self.txtRight.setText(_translate("MainWindow", "0"))
        self.txtBottom.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "Bottom"))
        self.btnCrop.setText(_translate("MainWindow", "Draw Rectangle..."))
        self.groupBox_4.setTitle(_translate("MainWindow", "4) Manipulate Image Channels"))
        self.label_4.setText(_translate("MainWindow", "You can manipulate the intensity of each channel of the isolated image. A window will open with sliders to the bottom allowing to set a factor to be multiplied with the respective image channel in real time:"))
        self.btnManipulate.setText(_translate("MainWindow", "Manipulate Isolated Image Channels"))
        self.groupBox_7.setTitle(_translate("MainWindow", "5) Calibration"))
        self.txtMicrometers.setText(_translate("MainWindow", "1"))
        self.btnDetermine.setText(_translate("MainWindow", "Determine..."))
        self.txtPixels.setText(_translate("MainWindow", "1"))
        self.label_11.setText(_translate("MainWindow", "µm / pixel"))
        self.btnEqual.setText(_translate("MainWindow", "="))
        self.label_12.setText(_translate("MainWindow", "/"))
        self.txtMPP.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "pixels"))
        self.label_6.setText(_translate("MainWindow", "µm"))
        self.groupBox_3.setTitle(_translate("MainWindow", "6) Export settings"))
        self.label_5.setText(_translate("MainWindow", "Images can be saved in the respective window by clicking the Save Button in the bottom toolbar."))
        self.chbExcel.setText(_translate("MainWindow", "Export Excel with a line for each detected grain / contour:"))
        self.btnExcel.setText(_translate("MainWindow", "Browse..."))
        self.label_10.setText(_translate("MainWindow", "(Leave blank to save to Original Image file path with *.xlsx-ending.)"))
        self.chbEval.setText(_translate("MainWindow", "Export Evaluation Image:"))
        self.chbIndex.setText(_translate("MainWindow", "Draw Index Number"))
        self.chbContours.setText(_translate("MainWindow", "Draw Contours"))
        self.chbFitting.setText(_translate("MainWindow", "Draw Fitting (Ellipse/Circle)"))
        self.chbAngle.setText(_translate("MainWindow", "Draw Orientation Angle"))
        self.btnEvalBrowse.setText(_translate("MainWindow", "Browse..."))
        self.groupBox_6.setTitle(_translate("MainWindow", "Help / About"))
        self.btnHelp.setText(_translate("MainWindow", "Help"))
        self.label_9.setText(_translate("MainWindow", "Version: 0.1b"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Check out this git for new releases and documentation: <a href=\"https://github.com/legnad/eichkoernchen\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/legnad/eichkoernchen</span></a></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Author: Christian Hofmann, 2019"))
        self.groupBox_5.setTitle(_translate("MainWindow", "7) Go!"))
        self.btnThreshold.setText(_translate("MainWindow", "Thresholding"))
        self.btnResult.setText(_translate("MainWindow", "Show Result"))
        self.btnExport.setText(_translate("MainWindow", "Export Excel and Result Image"))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

